package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carol
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastrarMorador = new javax.swing.JMenuItem();
        menuCadastrarResidencia = new javax.swing.JMenuItem();
        menuCadastrarProprietario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuEditarMorador = new javax.swing.JMenuItem();
        menuEditarResidencia = new javax.swing.JMenuItem();
        menuEditarProprietario = new javax.swing.JMenuItem();
        listar = new javax.swing.JMenu();
        listarProprietario = new javax.swing.JMenuItem();
        listarMorador = new javax.swing.JMenuItem();
        menuMensalidadeEditar = new javax.swing.JMenu();
        menuMensalidade = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastrar");

        menuCadastrarMorador.setText("Morador");
        menuCadastrarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarMoradorActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarMorador);

        menuCadastrarResidencia.setText("Residência");
        menuCadastrarResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarResidenciaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarResidencia);

        menuCadastrarProprietario.setText("Proprietário");
        menuCadastrarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarProprietarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarProprietario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        menuEditarMorador.setText("Morador");
        menuEditarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarMoradorActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditarMorador);

        menuEditarResidencia.setText("Residência");
        menuEditarResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarResidenciaActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditarResidencia);

        menuEditarProprietario.setText("Proprietário");
        menuEditarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarProprietarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditarProprietario);

        jMenuBar1.add(jMenu2);

        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        listarProprietario.setText("Proprietário");
        listarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProprietarioActionPerformed(evt);
            }
        });
        listar.add(listarProprietario);

        listarMorador.setText("Morador");
        listarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMoradorActionPerformed(evt);
            }
        });
        listar.add(listarMorador);

        jMenuBar1.add(listar);

        menuMensalidadeEditar.setText("Mensalidade");

        menuMensalidade.setText("Controle Cadastro");
        menuMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMensalidadeActionPerformed(evt);
            }
        });
        menuMensalidadeEditar.add(menuMensalidade);

        jMenuItem3.setText("Controle Editar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuMensalidadeEditar.add(jMenuItem3);

        jMenuBar1.add(menuMensalidadeEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarMoradorActionPerformed
        this.dispose();
        CadastrarMorador cm;
        try {
            cm = new CadastrarMorador();
            cm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuCadastrarMoradorActionPerformed

    private void menuCadastrarResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarResidenciaActionPerformed
        this.dispose();
        CadastrarResidencia cr;
        try {
            cr = new CadastrarResidencia();
            cr.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuCadastrarResidenciaActionPerformed

    private void menuEditarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarMoradorActionPerformed
        this.dispose();
        EditarMorador ed;
        try {
            ed = new EditarMorador();
            ed.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuEditarMoradorActionPerformed

    private void menuEditarResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarResidenciaActionPerformed
        this.dispose();
        EditarResidencia er;
        try {
            er = new EditarResidencia();
            er.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuEditarResidenciaActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        this.dispose();
        ListarProprietario listar;
        try {
            listar = new ListarProprietario();
            listar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listarActionPerformed

    private void menuCadastrarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarProprietarioActionPerformed
        this.dispose();
        CadastrarProprietario cp;
        try {
            cp = new CadastrarProprietario();
            cp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCadastrarProprietarioActionPerformed

    private void menuMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMensalidadeActionPerformed
        this.dispose();
        CadastrarCondominioMensalidade mensalidade;
        try {
            mensalidade = new CadastrarCondominioMensalidade();
            mensalidade.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuMensalidadeActionPerformed

    private void listarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProprietarioActionPerformed
        this.dispose();
        ListarProprietario lp;
        try {
            lp = new ListarProprietario();
            lp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listarProprietarioActionPerformed

    private void menuEditarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarProprietarioActionPerformed
        this.dispose();
        EditarProprietario ep;
        try {
            ep = new EditarProprietario();
            ep.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuEditarProprietarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        EditarCondominioMensalidade em;
        try {
            em = new EditarCondominioMensalidade();
            em.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void listarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMoradorActionPerformed
        this.dispose();
        try {
            ListarMorador lm = new ListarMorador();
            lm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listarMoradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu listar;
    private javax.swing.JMenuItem listarMorador;
    private javax.swing.JMenuItem listarProprietario;
    private javax.swing.JMenuItem menuCadastrarMorador;
    private javax.swing.JMenuItem menuCadastrarProprietario;
    private javax.swing.JMenuItem menuCadastrarResidencia;
    private javax.swing.JMenuItem menuEditarMorador;
    private javax.swing.JMenuItem menuEditarProprietario;
    private javax.swing.JMenuItem menuEditarResidencia;
    private javax.swing.JMenuItem menuMensalidade;
    private javax.swing.JMenu menuMensalidadeEditar;
    // End of variables declaration//GEN-END:variables
}
